### ISSUE TITLE
Quadwar RTS game TODO list

### ISSUE THREAD

**Issue by automainint** [automainint/laplace#37]
- [x] Game lobby UI & basic behaviour
  - [x]  Entering
  - [x] Leaving
  - [x] Starting
- [x] Game launching
- [x] Landscape generation & graphics
- [x] Player camera controls
- [x] Spawn starting units
- [x] Unit basic graphics
- [x] Unit basic selection
- [ ] Unit controls
- [ ] Unit UI
- [x] Pathmap
- [x] Unit basic movement - #7 
- [ ] Unit pathfinding - #21 
- [ ] Unit attack
- [ ] Unit visibility & fog of war
- [ ] Game win conditions
- [ ] Game chat
- [ ] Save & load
- [ ] Event sounds
- [ ] Background audio
- [ ] Improved graphics
- [ ] Improved animation
- [ ] Global lobby
- [ ] Multiplayer server - #33 
- [ ] Player authentication
- [ ] Player profile
- [ ] Ranking system
- [ ] Linux server build - #15  #33
